version: '2'

services:
  redis:
    image: redis
    container_name: cache
    expose:
      - 6379
    networks:
      - deploy

  app:
    restart: 'always'
    image: worffl
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./logs:/usr/src/app/logs
      - worffl_certs:/etc/certs
    ports:
      - 3000:3000
    networks:
      - deploy
      - node

networks:
  deploy:

  node:
    external:
      name: node

volumes:
  worffl_certs:
