redis:
  image: redis
  container_name: cache
  expose:
    - 6379
app:
  build: ./
  volumes:
    - ./:/var/www/app
links:
    - redis
  ports:
    - 5000:5000
  environment:
    - REDIS_URL=redis://cache
